"""XLeVR configuration. Edit defaults here directly."""

import os
from dataclasses import dataclass, field
from typing import Dict


@dataclass
class XLeVRConfig:
    # Network
    https_port: int = 8443
    websocket_port: int = 8442
    host_ip: str = "0.0.0.0"

    # SSL — auto-generated by ensure_ssl_certificates() if missing
    certfile: str = "cert.pem"
    keyfile: str = "key.pem"

    # Control
    enable_vr: bool = True
    enable_https: bool = True
    vr_to_robot_scale: float = 1.0

    # Grip-pose corrections that align the EE frame with the user's natural
    # wrist axes. Applied as R_g2ee = R_z(±grip_yaw_deg) @ R_g2ee_rake.
    #
    # grip_rake_deg: pitch tilt of controller handle from EE +Z (vertical) at
    #   natural grip. Meta Quest 3 typical: 40–50°.
    # grip_yaw_deg: magnitude of inward wrist yaw at natural grip. Tune if a pure
    #   physical wrist yaw doesn't map to a pure EE-yaw (cross-couples into
    #   roll/pitch).
    grip_rake_deg: float = 40.0
    grip_yaw_deg: float = 12.0

    # Camera feed URL for the desktop web UI (MJPEG or still-image endpoint).
    # Leave empty to disable camera feed button.
    camera_feed_url: str = ""

    # ── In-VR camera stream (pushed over the existing WSS) ──────────────────
    # Conservative defaults so streaming can't starve the Quest's pose loop;
    # tune up if your headset/link has headroom.
    camera_stream_fps: int = 10       # broadcaster publish rate (decoupled from control loop)
    camera_jpeg_quality: int = 70     # cv2 JPEG quality 0-100
    camera_max_width: int = 320       # downscale frames wider than this before encoding
    camera_max_feeds: int = 3         # max simultaneous feeds shown in VR

    # Device ports — overridden by vr_monitor from robot config when needed
    follower_ports: Dict[str, str] = field(
        default_factory=lambda: {"left": "/dev/ttyACM0", "right": "/dev/ttyACM1"}
    )

    @property
    def ssl_files_exist(self) -> bool:
        return os.path.exists(self.certfile) and os.path.exists(self.keyfile)

    def ensure_ssl_certificates(self) -> bool:
        from .utils import ensure_ssl_certificates
        return ensure_ssl_certificates(self.certfile, self.keyfile)
